### PR TITLE
Add support for mip

### PR DESCRIPTION
**Pull request by brainelectronics**
### Added
- `package.json` file and installation instruction for `mip` usage, see #30
- `utemplate` is part of this package to be independent from other packages, see #30
- Content of `package.json` is validated on each test workflow run
- GitHub issues template files

### Removed
- Dependency to `micropython-ulogging` and `utemplate` packages in `setup.py` file

### Fixed
- YAML syntax in all workflow files

### CODE REVIEW

**Comment by brainelectronics** [comment]
May you want to test it as well @ned-pcs? It works as expected on my side

**Comment by ned-pcs** [comment]
I followed your new directions, and the install went well into `/lib` but `/boot.py` and `/main.py` didn't get installed. I manually copied those onto the board, rebooted, and everything seemed to work.

Should `Passwort` be `Password` (it looks like the rest of the UI is in English)?

**Comment by ned-pcs** [comment]
It looks like `mip` wants to install everything mentioned in `package.json` under `/lib`. Perhaps the logic for `main.py` and `boot.py` should be installed under `/lib/wifi_manager` and then either copied to the root, or imported from `/boot.py` and `/main.py`.

**Comment by brainelectronics** [comment]
relates to #32

**Review by brainelectronics — COMMENTED** [review]
LGTMyself

**Pull request merged**
